import fs from 'fs-extra';
import path from 'path';
import { runCommand, tryCommand } from '../utils/command';
import { resolveSafePath } from '../utils/pathUtils';
import {
  ShareEntry,
  ShareType,
  loadShareState,
  removeShare,
  upsertShare,
  clearShares,
} from './shareState';
import { NAS_USER, USERNAME_MAP_PATH, ensureUsernameMap } from './nasUserConfig';
import { env } from '../config/env';

const SAMBA_CONFIG_PATH = env.sambaConfigPath;
const SMB_HOST = env.publicSmbHost || env.publicBaseUrl;
const MANAGED_START = '# BEGIN GVTNAS SHARES';
const MANAGED_END = '# END GVTNAS SHARES';

interface EnableSharePayload {
  shareName: string;
  mountPoint: string;
  type: ShareType;
  maxSizeGb?: number;
}

export async function enableShare(payload: EnableSharePayload): Promise<ShareEntry> {
  const sanitizedName = sanitizeShareName(payload.shareName);
  const mountPoint = resolveSafePath(payload.mountPoint);
  await assertPathExists(mountPoint);

  const entry: ShareEntry = {
    shareName: sanitizedName,
    mountPoint,
    type: payload.type,
    smbPath: `smb://${SMB_HOST}/${sanitizedName}`,
    options: buildShareOptions(payload),
  };

  await upsertShare(entry);
  await syncSambaConfig();
  await restartSamba();
  return entry;
}

export async function disableShare(shareName: string): Promise<void> {
  await removeShare(shareName);
  await syncSambaConfig();
  await restartSamba();
}

export async function resetAllShares(): Promise<void> {
  await clearShares();
  await syncSambaConfig();
  await restartSamba();
}

export async function listShares(): Promise<ShareEntry[]> {
  const state = await loadShareState();
  return state.shares;
}

async function assertPathExists(target: string): Promise<void> {
  const exists = await fs.pathExists(target);
  if (!exists) {
    throw new Error(`Mount point ${target} not found`);
  }
}

function sanitizeShareName(name: string): string {
  return name.trim().replace(/[^A-Za-z0-9_-]/g, '-');
}

function buildShareOptions(payload: EnableSharePayload): Record<string, string | number | boolean> {
  if (payload.type === 'timeMachine') {
    const options: Record<string, string | number | boolean> = {
      'fruit:time machine': 'yes',
      'vfs objects': 'catia fruit streams_xattr',
    };
    if (payload.maxSizeGb && payload.maxSizeGb > 0) {
      options['fruit:time machine max size'] = `${payload.maxSizeGb}G`;
    }
    return options;
  }
  return {};
}

async function syncSambaConfig(): Promise<void> {
  await ensureUsernameMap();
  const shares = await listShares();
  const managedBlock = buildManagedBlock(shares);
  const baseConfig = buildDefaultConfig();
  const nextConfig = `${baseConfig.trim()}\n\n${managedBlock}\n`;
  await fs.ensureDir(path.dirname(SAMBA_CONFIG_PATH));
  await fs.writeFile(SAMBA_CONFIG_PATH, nextConfig, 'utf8');
}

function buildManagedBlock(shares: ShareEntry[]): string {
  if (shares.length === 0) {
    return `${MANAGED_START}\n# No managed shares yet\n${MANAGED_END}`;
  }
  const entries = shares.map(renderShare).join('\n\n');
  return `${MANAGED_START}\n${entries}\n${MANAGED_END}`;
}

function renderShare(share: ShareEntry): string {
  const baseLines = [
    `[${share.shareName}]`,
    `   path = ${share.mountPoint}`,
    '   browseable = yes',
    '   read only = no',
    '   guest ok = no',
    '   public = no',
    `   valid users = ${NAS_USER}`,
    `   force user = ${NAS_USER}`,
    `   force group = ${NAS_USER}`,
    '   create mask = 0775',
    '   directory mask = 0775',
    `   comment = Managed by GVTNAS (${share.type})`,
  ];

  if (share.options) {
    for (const [key, value] of Object.entries(share.options)) {
      baseLines.push(`   ${key} = ${value}`);
    }
  }

  return baseLines.join('\n');
}

function buildDefaultConfig(): string {
  return `# Generated by GVTNAS
[global]
   workgroup = WORKGROUP
   server role = standalone server
   security = user
   map to guest = never
   username map = ${USERNAME_MAP_PATH}
   server min protocol = SMB2
   server max protocol = SMB3
   usershare allow guests = no`;
}

async function restartSamba(): Promise<void> {
  const attempts = [
    ['systemctl', 'reload', 'smbd'],
    ['systemctl', 'restart', 'smbd'],
    ['service', 'smbd', 'reload'],
    ['service', 'smbd', 'restart'],
    ['pkill', '-HUP', 'smbd'],
  ];

  for (const attempt of attempts) {
    const result = await tryCommand(attempt[0], attempt.slice(1));
    if (result) {
      return;
    }
  }

  // Final attempt: log but do not throw to avoid crashing backend.
  console.warn('Unable to restart Samba automatically. Please restart manually.');
}
